services:
  app:
    container_name: modclub_src
    environment:
      DFX_VERSION: 0.20.1
      NODE_VERSION: 21.5.0
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
