[dependencies]
uuid = "https://github.com/aviate-labs/uuid.mo#v0.2.0"
array = "https://github.com/aviate-labs/array.mo#v0.1.1"
crypto = "https://github.com/aviate-labs/crypto.mo#v0.2.0"
rand = "https://github.com/aviate-labs/rand.mo#v0.2.2"
json = "https://github.com/aviate-labs/json.mo#v0.2.1"
parser-combinators = "https://github.com/aviate-labs/parser-combinators.mo#v0.1.1"
motoko-sequence = "https://github.com/matthewhammer/motoko-sequence#master@366c4191d856ed4842267f5ab89d7222ed2d71d0"
motoko-matchers = "https://github.com/kritzcreek/motoko-matchers#master@3dac8a071b69e4e651b25a7d9683fe831eb7cffd"
motoko-datetime = "https://github.com/ByronBecker/motoko-datetime#v0.1.1"
"encoding.mo" = "https://github.com/aviate-labs/encoding.mo#master@2711d18727e954b11afc0d37945608512b5fbce2"
map = "9.0.1"
serde = "2.0.4"
base = "0.11.1"
http-types = "1.0.1"
linked-list = "0.1.0"
memory-region = "0.1.1"