steps:
  - uses: ravsamhq/notify-slack-action@v2.5.0
    if: always()
    with:
      status: ${{ job.status }}
      token: ${{ secrets.GITHUB_TOKEN }}
      notification_title: "{workflow} has {status_message}"
      message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>"
      footer: "Linked Repo <{repo_url}|{repo}> | <{workflow_url}|View Workflow>"
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.ENG_NOTIF_SLACK_HK }}
