# .github/workflows/notify_slack_action.yml
on:
  # Trigger the workflow on all push and pull request events
  push:
  pull_request:

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - uses: ravsamhq/notify-slack-action@v2
        if: always()
        with:
          status: ${{ job.status }}
          token: ${{ secrets.GITHUB_TOKEN }}
          notification_title: "{workflow} has {status_message}"
          message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>"
          footer: "Linked Repo <{repo_url}|{repo}> | <{workflow_url}|View Workflow>"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ENGINEERING_NOTIFICATION_SLACK_HOOK }}