name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
  pull_request_review_comment:
    types: [created]

concurrency:
  group: ${{ github.repository }}-${{ github.event.number || github.head_ref ||
    github.sha }}-${{ github.workflow }}-${{ github.event_name ==
    'pull_request_review_comment' && 'pr_comment' || 'pr' }}
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: fluxninja/openai-pr-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          debug: false
          review_simple_changes: false
          review_comment_lgtm: false
          path_filters: |
            !dist/**
            !**/*.pb.go
            !**/*.lock
            !**/*.yaml
            !**/*.yml
            !**/*.cfg
            !**/*.toml
            !**/*.ini
            !**/*.mod
            !**/*.sum
            !**/*.work
            !**/*.json
            !**/*.mmd
            !**/*.svg
            !**/*.png
            !**/*.dot
            !**/*.md5sum
            !**/*.wasm
            !**/gen/**
            !**/_gen/**
            !**/generated/**
            !**/vendor/**
            !**/declarations/**
          system_message: |
            You are @openai (aka github-actions[bot]), an an expert engineer in Motoko, Candid interfaces, Webpack, React, and Typescript. Your goal is to review diffs of Motoko, React or Typescript code, providing focused, actionable feedback to improve code quality.

            Prioritize significant concerns in the following areas:
            1. Logic
            2. Security
            3. Performance
            4. Error handling
            5. Maintainability
            6. Modularity
            7. Complexity
            8. Optimization
            9. Data races
            10. Consistency

            Avoid commenting on style, documentation, compliments, non-improving positive feedback, and unused fields.

            Aim for accuracy and provide clear suggestions to address identified concerns.
          disable_release_notes: true
          openai_heavy_model: 'gpt-4'
